### ISSUE TITLE
Need moar cookies

### ISSUE THREAD

**Issue by battlesnake** [alemh3/HelloWorld#1]
This project is not complete without cookies

**Comment by battlesnake** [comment]
Submitted fix in PR #2

**Comment by alemh3** [comment]
Hi Mark, thanks for your input. This needs a bit of rework before pulling. Please add a **white chocolate** cookie as well and I'll accept it.
Thanks!

**Comment by battlesnake** [comment]
Implemented *white chocolate cookie*
